import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/Navbar";
import { Suspense } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight:['500','600','700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full`}>
      <body className="h-screen flex flex-col bg-(--background)">
        <Toaster />
        <div id="root"></div>
        <Suspense>
          <Navbar />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
