import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/Navbar";
import { Suspense } from "react";
import GlobalQueryProvider from "./_components/providers/GlobalQueryProvider";
import AppProvider from "./_components/providers/AppProvider";
import { SessionProvider } from "next-auth/react";
import SocketProvider from "./_components/providers/SocketProvider";
import VideoCallProvider from "./_components/providers/VideoCallProvider";
import Socket, { CallingFnProvider } from "./_components/socket-listeners/Socket";
import VideoCallWrapper from "./_components/video_call/VideoCallWrapper";
import UserProvider from "./_components/providers/UserProvider";
import PhoneNav from "./_components/navbar/PhoneNav";
import PhoneTopBar from "./_components/navbar/PhoneTopBar";
import PlaceHolderDiv from "./_components/PlaceHolderDiv";
import Sidebar from "./_components/navbar/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight:['500','600','700']
});


export const metadata = {
  title: "Tahfeez Dohad",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full`}>
      <body className=" bg-(--bg-main) h-full">
        <GlobalQueryProvider>
          <SessionProvider>
            <UserProvider>
              <SocketProvider>
                <AppProvider>
                  <VideoCallProvider>
                    <CallingFnProvider>
                      {/* <Socket /> */}
                      <Toaster />
                      <VideoCallWrapper />
                      <div id="root"></div>
                      <div id="video"></div>
                      <Suspense>
                        {/* <Navbar /> */}
                        <div className="flex flex-col lg:h-screen  lg:min-w-full">
                              <PhoneTopBar />
                          <div className="lg:flex lg:min-h-full">
                            <Sidebar />
                            <div className="min-w-40 hidden lg:block border"></div>
                            <div className="w-full ">
                              {children}
                            </div>
                          </div>
                          <PlaceHolderDiv />
                        </div>
                        <PhoneNav />
                      </Suspense>
                    </CallingFnProvider>
                  </VideoCallProvider>
                </AppProvider>
              </SocketProvider>
            </UserProvider>
          </SessionProvider>
        </GlobalQueryProvider>
      </body>
    </html>
  );
}
